export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

export const GET_TODO_TAGS_REQUEST = 'GET_TODO_TAGS_REQUEST';
export const GET_TODO_TAGS_SUCCESS = 'GET_TODO_TAGS_SUCCESS';
export const GET_TODO_TAGS_FAILURE = 'GET_TODO_TAGS_FAILURE';

export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE';
