export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const UPDATE_TODO_STATUS_REQUEST = 'UPDATE_TODO_STATUS_REQUEST';
export const UPDATE_TODO_STATUS_SUCCESS = 'UPDATE_TODO_STATUS_SUCCESS';
export const UPDATE_TODO_STATUS_FAILURE = 'UPDATE_TODO_STATUS_FAILURE';
export const SET_FILTER = 'SET_FILTER';
export const SET_TODO_SEARCH_TEXT = 'SET_TODO_SEARCH_TEXT';

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';
export const SET_TAG_SEARCH_TEXT = 'SET_TAG_SEARCH_TEXT';

export const GET_TAG_REQUEST = 'GET_TAG_REQUEST';
export const GET_TAG_SUCCESS = 'GET_TAG_SUCCESS';
export const GET_TAG_FAILURE = 'GET_TAG_FAILURE';

export const UPSERT_TAG_REQUEST = 'UPSERT_TAG_REQUEST';
export const UPSERT_TAG_SUCCESS = 'UPSERT_TAG_SUCCESS';
export const UPSERT_TAG_FAILURE = 'UPSERT_TAG_FAILURE';

export const GET_TODO_TAGS_REQUEST = 'GET_TODO_TAGS_REQUEST';
export const GET_TODO_TAGS_SUCCESS = 'GET_TODO_TAGS_SUCCESS';
export const GET_TODO_TAGS_FAILURE = 'GET_TODO_TAGS_FAILURE';

export const UPSERT_TODO_REQUEST = 'UPSERT_TODO_REQUEST';
export const UPSERT_TODO_SUCCESS = 'UPSERT_TODO_SUCCESS';
export const UPSERT_TODO_FAILURE = 'UPSERT_TODO_FAILURE';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE';

export const RESTORE_TODO_REQUEST = 'RESTORE_TODO_REQUEST';
export const RESTORE_TODO_SUCCESS = 'RESTORE_TODO_SUCCESS';
export const RESTORE_TODO_FAILURE = 'RESTORE_TODO_FAILURE';
