export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const UPDATE_TODO_STATUS = 'UPDATE_TODO_STATUS';
export const SET_FILTER = 'SET_FILTER';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
